const mongoose = require("mongoose");
const Joi = require("joi");

let carsSchema = new mongoose.Schema({
  license_number: String,
  manufacturer_en: String,
  manufacturer_hb: String,
  model_en: String,
  model_hb: String,
  gearbox: String,
  year: String,
  color: String,
  finish_level: String,
  km: Number,
  status: String,
  branch: String,
  fuel_type: String,
  exp_ins: Date,
  exp_test: Date,
  last_treatment: Date,
  km_next_treatment: Number,
  date_next_treatment: Date,
  class: String,
  deductible: Number,
  coder: String,
  added_by: String,
  date_join: {
    type: Date, default: Date.now
  },
  images: Array,
  files: Array,
  last_test_date: Date,
  license_fee: Number,
  fee_paid: Boolean,
  insurance_coverage: String,
  date_policy_insurance: Date,
  mandatory_premium_amount: Number,
  third_party_premium_amount: Number,
  access_amount: Number,
  compulsory_payment_arrangement: String,
  third_party_payment_deployment: String,
  minimum_age: String,
  minimum_seniority: String,
  collective: String,
  mandatory_payment_method: String,
  third_party_payment_method: String,
  policy_number:String,
})
exports.CarsModel = mongoose.model("cars", carsSchema)

exports.validateCars = (_reqBody) => {
  let joiSchema = Joi.object({
    license_number: Joi.string().min(7).max(10).required(),
    manufacturer_en: Joi.string().min(2).max(150).required(),
    manufacturer_hb: Joi.string().min(2).max(150).required(),
    model_en: Joi.string().min(1).max(150).required(),
    model_hb: Joi.string().min(1).max(150).required(),
    gearbox: Joi.string().min(1).max(150).required(),
    year: Joi.string().min(2).max(10).required(),
    color: Joi.string().min(2).max(150).required(),
    finish_level: Joi.string().min(2).max(150).required(),
    km: Joi.number().min(2).max(500000).required(),
    status: Joi.string().min(2).max(150).required(),
    branch: Joi.string().min(2).max(150).required(),
    fuel_type: Joi.string().min(2).max(150).required(),
    exp_ins: Joi.date().min("1-1-2023").max("1-1-2100").required(),
    exp_test: Joi.date().min("1-1-2020").max("1-1-2100").required(),
    last_treatment: Joi.date().min("1-1-2000").max("1-1-2100").allow(null, ""),
    km_next_treatment: Joi.number().min(2).max(500000).allow(null, ""),
    date_next_treatment: Joi.date().min("1-1-2023").max("1-1-2100"),
    class: Joi.string().min(1).max(150).required(),
    deductible: Joi.number().min(2).max(20000).required(),
    coder: Joi.string().min(2).max(20).allow(null, ""),
    images: Joi.array().min(0).max(100).allow(null, ""),
    files: Joi.array().min(0).max(100).allow(null, ""),
    last_test_date: Joi.date().min("1-1-2020").max("1-1-2100").allow(null, ""),
    license_fee: Joi.number().min(2).max(10000).allow(null, ""),
    fee_paid: Joi.boolean(),
    insurance_coverage: Joi.string().min(2).max(2030).allow(null, ""),
    date_policy_insurance: Joi.date().min("1-1-2020").max("1-1-2100").allow(null, ""),
    mandatory_premium_amount: Joi.number().min(2).max(112030).allow(null, ""),
    third_party_premium_amount: Joi.number().min(2).max(112030).allow(null, ""),
    minimum_age: Joi.string().min(2).max(2030).allow(null, ""),
    minimum_seniority: Joi.string().min(0).max(2030).allow(null, ""),
    collective: Joi.string().min(2).max(2030).allow(null, ""),
    mandatory_payment_method: Joi.string().min(2).max(2030).allow(null, ""),
    third_party_payment_method: Joi.string().min(2).max(2030).allow(null, ""),
    policy_number: Joi.string().min(2).max(2030).allow(null, ""),
    access_amount:Joi.number().min(1).max(12000).allow(null, ""),
    compulsory_payment_arrangement:Joi.string().min(2).max(2030).allow(null, ""),
    third_party_payment_deployment:Joi.string().min(2).max(2030).allow(null, ""),
  })
  return joiSchema.validate(_reqBody)
}